## 行列演算の基礎


$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [2]:
import numpy as np

In [7]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [13]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [15]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [18]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い

In [24]:
x = np.array([1, 2, 3]) # 一重[]の時
print(x)

[1 2 3]


In [25]:
print(x.T) # 正常に転置できない

[1 2 3]


In [64]:
x = np.array([[1, 2, 3]])
print(x)

[[1 2 3]]


In [30]:
print(x.T) # 二重にすると、正常に転置できる

[[1]
 [2]
 [3]]


# Numpyでよく使う処理

In [34]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]
]) # こんな感じで、改行をうまく使う

In [33]:
print(X)

[[2 3 4]
 [1 2 3]]


In [35]:
X.shape

(2, 3)

In [39]:
row, col = X.shape # 行・列の数を取得できる

In [37]:
row


2

In [38]:
col

3

In [41]:
for x in X:
    print(x)
    print('---')

[2 3 4]
---
[1 2 3]
---


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
, \ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- step1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- step4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [43]:
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])
print(X)


[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [44]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [45]:
Xt = X.T

# step1
XtX = np.dot(Xt, X)
print(XtX)

In [60]:
# step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [63]:
# step3
Xty = np.dot(Xt, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [62]:
# step4
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [66]:
import sklearn 

In [68]:
# 重回帰分析のみを読み込み
from sklearn.linear_model import LinearRegression

In [70]:
# モデルの宣言
model = LinearRegression()

In [72]:
# モデルの学習 == パラメータの調整
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [73]:
# 調整後のパラメータ coefは「係数」と言う意味
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [75]:
# 切片を表示
model.intercept_

array([-0.14285714])

In [78]:
# 予測精度 ← 決定係数 0 ~ 1 で判定
# １に近いほど精度が高い
model.score(X, y)

0.6923076923076923

In [79]:
# 予測値の計算
x = np.array([
    [1, 2, 3]
])


In [81]:
y_pred = model.predict(x)
print(y_pred)
# fitで学習させて、predictで予測する


[[3.]]
